# Generated by Django 5.2.11 on 2026-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='salom', max_length=128),
            preserve_default=False,
        ),
    ]
