# Generated by Django 5.2.11 on 2026-03-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_category_created_at_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='author',
            name='about_en',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='author',
            name='about_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='author',
            name='about_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='author',
            name='professions_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Professions'),
        ),
        migrations.AddField(
            model_name='author',
            name='professions_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Professions'),
        ),
        migrations.AddField(
            model_name='author',
            name='professions_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Professions'),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description_en',
            field=models.TextField(null=True, verbose_name='Long description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='Long description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description_uz',
            field=models.TextField(null=True, verbose_name='Long description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.CharField(max_length=255, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='authors/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='author',
            name='professions',
            field=models.CharField(max_length=128, verbose_name='Professions'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_name='blogs', to='blogs.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blogs.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='long_description',
            field=models.TextField(verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogs.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blogs.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
