# Generated by Django 5.2.11 on 2026-03-04 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='manufacturers/', verbose_name='Logo')),
                ('country', models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country')),
                ('country_en', models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country')),
                ('country_uz', models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country')),
                ('country_ru', models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Manufacture',
                'verbose_name_plural': 'Manufactures',
                'db_table': 'manufacture',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, verbose_name='Name')),
                ('name_en', models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, null=True, verbose_name='Name')),
                ('hex_code', models.CharField(help_text='e.g. #8B4513', max_length=7, verbose_name='HEX Code')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'db_table': 'product_tag',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('icon', models.CharField(help_text="CSS icon class, e.g. 'fa fa-couch'", max_length=255, verbose_name='Icon')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('sku', models.CharField(help_text='Stock Keeping Unit — unique product code', max_length=64, unique=True, verbose_name='SKU')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=512, verbose_name='Short description')),
                ('short_description_en', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('short_description_uz', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('short_description_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Main Image')),
                ('price_uzs', models.DecimalField(decimal_places=2, help_text='Price in Uzbek Sum', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (UZS)')),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Price in US Dollar', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (USD)')),
                ('price_rub', models.DecimalField(decimal_places=2, help_text='Price in Russian Ruble', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (RUB)')),
                ('discount_price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Price (UZS)')),
                ('discount_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Price (USD)')),
                ('discount_price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Price (RUB)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('DISCONTINUED', 'Discontinued'), ('COMING_SOON', 'Coming Soon')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.manufacture', verbose_name='Manufacture')),
                ('categories', models.ManyToManyField(related_name='products', to='products.productcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColorQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this color', verbose_name='Quantity')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantities', to='products.productcolor', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_quantities', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Color Quantity',
                'verbose_name_plural': 'Product Color Quantities',
                'db_table': 'product_color_quantity',
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductColorQuantity', to='products.productcolor', verbose_name='Colors'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary gallery image', verbose_name='Is primary')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_image',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag', verbose_name='Tags'),
        ),
    ]
